### ISSUE TITLE
how to steup by aliyun oss?

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [baobao1270/thunderbird-s3-filelink-provider#3]
This configuration doesn't work.
![image](https://github.com/baobao1270/thunderbird-s3-filelink-provider/assets/67987607/5744a87c-2afa-43e8-92c7-32f16ddad6eb)

**Comment by baobao1270** [comment]
Aliyun OSS requires RFC 3986 URI encoding, which not used in previous version. Now it should be fixed in v1.1.0 (88e5c45).

Here are the steps to setup Aliyun OSS
以下是设置阿里云 OSS 的详细步骤：

 1. Create a bucket with `Public Read` ACL
    创建一个「**公共读**」权限的 Bucket
    ![image](https://github.com/baobao1270/thunderbird-s3-filelink-provider/assets/7949769/3938680f-e517-4b47-b26e-cb9867442ee4)
    > **Why we use `Public Read` ACL?**
    > **为什么使用「公共读」权限？**
    >
    > Email is static, once sent, you can't modify it. You also can't run JavaScript in a email. So if we can't calculate the signature for get the object at receiver end. If we calculate the signature when sending the email, the link may expire before the receiver opens it.
    > 电子邮件是静态的也没，一旦送出就无法修改。同时，电子邮件虽然是 HTML，但是也无法执行 JavaScript。因此在接收端计算获取文件的签名是不可能的。如果在发送时计算，那么该签名可能在收件人打开之前过期。

 2. Add a RAM user at RAM Console. Check `OpenAPI Access` in `Access Mode`. Take a note of the `Access Key` and `Secret Key`, which will be filled in S3 Filelink plugin settings.
    在 RAM 控制台添加一个新用户，在「访问模式」选项中，勾选「OpenAPI 访问」。记录生成的 AK 和 SK，该 AK/SK 即为配置插件时填写的 AK/SK。
    For Aliyun CN, create user at: https://ram.console.aliyun.com/users/create
    For Alibaba Cloud International, find the IAM Console link in your Alibaba Cloud Console.
    对于中国版阿里云，在 https://ram.console.aliyun.com/users/create 创建用户。对于国际版，您需要在您的阿里云控制台找到 IAM 控制台链接。

 3. Back to OSS Console. Under the `Permission Control - Bucket Policy` sidebar menu, click `Authorize` button. 
    回到 OSS 控制台，在 「权限控制」——「Bucket 授权策略」选项下，点击「新增授权」按钮。
    ![image](https://github.com/baobao1270/thunderbird-s3-filelink-provider/assets/7949769/ff5bfde3-0a7b-414a-82fb-79e3ed9b2be3)

 4. On Authorize page, check the `RAM User` and select the user you just created in step 2. Select `Read/Write` under `Authorized Operation` section. Then click `OK`.
    在 「新增授权」页面，勾选「子账户」，并选择在第 2 步创建的用户。「授权操作」选择「读/写」。点击「确定」为该用户授权。
   ![image](https://github.com/baobao1270/thunderbird-s3-filelink-provider/assets/7949769/32c5ffcb-1aaa-47d9-9185-3859105f6875)

 5. Setup the S3 Filelink plugin. Fill the form as follows:
    配置插件。按以下方式填写表单：
     - Endpoint: The `Endpoint` of `Access Over Internet` shown in `Port` section, `Overview` page on OSS Console. Example: `oss-cn-hangzhou.aliyuncs.com`
       Endpoint: OSS 控制台「概览」页面下「访问端口」一节，「公网访问」的「Endpoint（地域节点）」地址。例如：`oss-cn-hangzhou.aliyuncs.com`
     - Region: Your bucket region, like `cn-hangzhou`
       Region: 您的 bucket 地域，例如：`cn-hangzhou`
     - Bucket: Your bucket name
       Bucket: 您的 bucket 名称
     - Prefix: The prefix (folder) to save attachments. **Can't be empty, and using root directory `/` is not supported.**
       Prefix: 您保存附件的前缀（文件夹）。**不能为空，也不支持使用根路径 `/`**
     - Access Key & Secret Key: The Access Key & Secret Key of IAM user you created.
       Access Key & Secret Key: 您创建的 IAM 用户的 AK/SK
     - Remember to click `Save`.
       记得点击「保存」。
       ![image](https://github.com/baobao1270/thunderbird-s3-filelink-provider/assets/7949769/ab5e7a80-e07c-46e8-9cbd-93bda86bc5ec)

**Comment by Mr-Ao-Dragon** [comment]
tks！这非常有用？
